version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/node/app'
      - '/home/node/app/node_modules'
    ports:
      - "5000:5000"
     # - "9443:9443"    SSL
