version: "3"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - "5000:5000"
     # - "9443:9443"    SSL
